### ISSUE TITLE
Can't grant access to profile or user after install

### ISSUE THREAD

**Issue by rossreicks** [zuppio/zuppio#1]
**Describe the issue**
After installing the zuppio navigator within my org for Admin's only, I am unable to manually grant access to a separate profile or user. I have gone through each exposed class and object and assigned permissions to the new profile but I am unable to grant access to 5 of the 10 objects because they are not visible outside the managed package.

The error I am receiving is:
```
Access Violation Exception : (Zuppio) FIELD_ACCESS_VIOLATION - NO_SELECT : Zuppio__Authorization_Details__c => Name , Zuppio__Reauthorization_Needed__c , Zuppio__Authorized_On__c , Zuppio__Limited_Access__c; \nZuppio__Hub_Member_Control__c => Name , Zuppio__Hidden__c , Zuppio__Never_Deploy__c
```

**To Reproduce**
* Install package version 40 in an org and choose the option for admins only.
* Create a user with the profile Standard User
* Grant Standard user access to Zuppio navigator app
* Grant full permissions to all Zuppio Objects and Tabs
* Grant Access to Zuppio Apex classes provided by the package
* Login as user and notice you are unable to use zuppio effectively

**Expected behavior**
Should be able to more easily grant access to users outside of the System Admin profile

**Screenshots**
![Screenshot 2024-07-10 at 2 10 25 PM](https://github.com/zuppio/zuppio/assets/80704623/ab6c1d7f-bde5-475d-812c-bac8659315ce)

**Browser/Device:**
 - Browser: Chrome
 - ZuppIO placement: Salesforce Package
 - ZuppIO Version: 1.40.0

**Comment by rossreicks** [comment]
I have now also tried to uninstall the app and reinstall the app explicitly specifying to install the app for that specific profile. It did not grant access to the profile

**Comment by JIuckman** [comment]
@rossreicks Can you check the Schema Settings to enable some settings like in the picture?
![image](https://github.com/user-attachments/assets/3b350899-dd9b-4a73-b4a7-bf9bc960e9ba)
Also make sure that you have the read permission for custom setting configured.

**Comment by rossreicks** [comment]
I ended up making a custom permission set from the admin profile with all the zuppio namespace items and that worked. I can close this issue.
